services:
  db:
    image: postgres:16-alpine
    container_name: payment-selection-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: payment_selection_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      # Configurações de performance
      POSTGRES_SHARED_PRELOAD_LIBRARIES: pg_stat_statements
      POSTGRES_MAX_CONNECTIONS: 100
      POSTGRES_SHARED_BUFFERS: 256MB
      POSTGRES_EFFECTIVE_CACHE_SIZE: 1GB
      POSTGRES_WORK_MEM: 4MB
      POSTGRES_MAINTENANCE_WORK_MEM: 64MB
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d payment_selection_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    # Configurações de segurança
    security_opt:
      - no-new-privileges:true
    # Limites de recursos
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    # Configurações de logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  db_data:
    driver: local
    name: payment-selection-db-data


