server:
  port: 8080
  address: 0.0.0.0
  # Configuração do Graceful Shutdown
  shutdown: graceful

spring:
  application:
    name: payment-selection-backend
  
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_selection_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC

  # Configuração do Graceful Shutdown
  lifecycle:
    timeout-per-shutdown-phase: 30s

# Configuração do Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,configprops,beans,mappings,shutdown
      base-path: /actuator
  endpoint:
    health:
      show-details: when-authorized
      show-components: always
    shutdown:
      enabled: true
  health:
    defaults:
      enabled: true
    db:
      enabled: true
    diskspace:
      enabled: true
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

# Informações da aplicação para o endpoint /actuator/info
info:
  app:
    name: Payment Selection Backend
    description: Sistema de seleção de pagamentos em massa com paginação
    version: 1.0.0
    encoding: UTF-8
    java:
      version: 21

logging:
  level:
    com.example.paymentselection: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG

